### ISSUE TITLE
Cannot find module 'parcel-plugin-url-loader' from 'project-path/src/view'

### ISSUE THREAD

**Issue by JZLeung** [fansenze/parcel-plugin-url-loader#1]
my project directory structure:
```
├── src
│   ├── image
│   │   └── 1.jpg
│   ├── js
│   │   ├── common.js
│   │   ├── index.js
│   │   └── second.js
│   ├── styles
│   │   └── index.scss
│   └── view
│       ├── index.html
│       └── second.html
└── yarn.lock

15 directories, 44 files
```
usage: (second.js)
```javascript
import ImageSrc from '../image/1.jpg'

console.log('welcome to the second page.')

let img = document.createElement('img')
img.src = ImageSrc
document.body.appendChild(img)
```

when i want to build my project, it throw an error:
```bash
{17-12-26 18:22}Leung:~/workspace/parcel-demo@master✗✗✗✗✗✗ lynnleung% yarn build
yarn run v1.3.2
$ NODE_ENV=production && parcel build src/view/*.html -d build --public-url public
⏳  Building...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
🚨  /Users/lynnleung/workspace/parcel-demo/src/js/second.js: Couldn't find preset "env" relative to directory "/Users/lynnleung/workspace/parcel-demo"
Error: Cannot find module 'parcel-plugin-url-loader' from '/Users/lynnleung/workspace/parcel-demo/src/view'
    at /usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions (/usr/local/lib/node_modules/parcel-bundler/src/assets/JSAsset.js:55:20)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fansenze** [comment]
Make sure that you have already install `parcel-plugin-url-loader`  
Did you install `parcel-bundler` in global ?

**Comment by JZLeung** [comment]
1. sure installed.
2. yes. `npm i parcel-bundler -g`

if i run the script `yarn remove parcel-plugin-url-loader` ,to remove `parcel-plugin-url-loader` , `parcel build ` work well.

**Comment by fansenze** [comment]
sorry, i fix it in `1.0.5`
try to `yarn remove parcel-plugin-url-loader` and `yarn add parcel-plugin-url-loader --dev` again  

then you should create `.babelrc` configuration file and `yarn add babel-preset-env --save-dev`  
In order to enable the preset you have to define it in your `.babelrc` file, like this:  
```
{
  "presets": ["env"]
}
```

**Comment by JZLeung** [comment]
it work.
but it did not convert the picture to base64.
the picture is only 357Byte.
```html
<img src="f62e46ea2a3e922ac307ed6e4b481b5c.png" alt="">
```
```bash
{17-12-27 18:19}Leung:~/workspace/parcel-demo@vue✗✗✗✗✗✗ lynnleung% ll build -h | grep .png
ls: -h: No such file or directory
-rw-r--r--  1 lynnleung  staff   357B 12 27 18:18 f62e46ea2a3e922ac307ed6e4b481b5c.png
```

**Comment by fansenze** [comment]
did you import image in js?
and i suggest you install `parcel-bundler` in your project not in global

**Comment by JZLeung** [comment]
no, i import it in the html like this: 
```html
<img src="../image/add.png" alt="">
```
and i had remove the global `parcel-bundler` and install again in my project, it can't convert eighter.

**Comment by fansenze** [comment]
now, my plugin is only convert img in `.js`
you can understand it in `README.md`

**Comment by JZLeung** [comment]
i'm so sorry about it.
i try to import it from js, but the img's src is still the real path, not the base64:
here is my source. 
do i import it in a wrong way?
```js
import add from '../image/add.png'

let img = document.createElement('img')
img.src = add
document.body.appendChild(img)
```
the packaged js:
```js
...
({9:[function(require,module,exports) {
module.exports="f62e46ea2a3e922ac307ed6e4b481b5c.png";
},{}],13:[function(require,module,exports) {
"use strict";var e=require("../image/add.png"),d=t(e);function t(e){return e&&e.__esModule?e:{default:e}}var r=document.createElement("img");r.src=d.default,document.body.appendChild(r);
},{"../image/add.png":9}]},{},[13])
```

**Comment by fansenze** [comment]
your file size is more than 10kb ?
default configuration is <= 10240

**Comment by JZLeung** [comment]
no, only 357B:
```bash
src/image:
total 96
-rw-r--r--@ 1 lynnleung  staff   357B 12 26 14:50 add.png
```

**Comment by fansenze** [comment]
tell me:  
node verison  
parcel-bundler verison  
parcel-plugin-url-loader version

**Comment by JZLeung** [comment]
node: v8.9.1
parcel-bundler: 1.3.1
parcel-plugin-url-loader: 1.0.5
thx.

**Comment by fansenze** [comment]
did you have demo?
i try to `parcel html`, then i convert image to base64
and the image is less than 10kb

**Comment by JZLeung** [comment]
i have init another demo , install all the dependencies again . 
it can convert now . 😭

**Comment by fansenze** [comment]
maybe you forget to `rm -rf .cache`, `parcel` will generate `.cache`
